name: Auto approve
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: ${{ startsWith(github.head_ref, "release/") || startsWith(github.head_ref, "backport/") }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
