name: Auto approve
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'Release Slayer' || github.actor == 'imgbot'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
