name: Auto approve
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.base_ref == 'master' && startsWith(github.head_ref, 'release/') || github.base_ref == 'develop' && (startsWith(github.head_ref, 'backport/') || github.head_ref == 'imgbot')
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
